{
 "title": "DevPulse Dashboard",
 "refresh": "15s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"devpulse-backend\"})"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"devpulse-backend\",status=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"devpulse-backend\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"devpulse-backend\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"devpulse-backend\"}[5m])) by (le))",
     "legendFormat": "p95 latency"
    }
   ]
  }
 ]
}